name: 'Check & install Toolset'
description: 'Check & Install necessary toolset'
runs:
  using: "composite"
  steps:
      - name: Check Terraform
        run: |
          echo "* Terraform wil be installed."
          brew install terraform
          terraform --version

        