name: 'Check & install Toolset'
description: 'Check & Install necessary toolset'
inputs:
  OVERRIDE_LOCAL_VERSION:
    description: 'Name for Results (Publish Name)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: Check & Install toolset
        if: ${{ inputs.ARM_TENANT_ID}} == false
        run: bash ${{ github.action_path }}/src/install.sh
        shell: bash
  steps:
      - name: Check & Install Terraform
        if: ${{ inputs.ARM_TENANT_ID}} == true
        run: bash ${{ github.action_path }}/src/install.sh -o
        shell: bash
