name: 'Check & install Toolset'
description: 'Check & Install necessary toolset'
runs:
  using: "composite"
  steps:
      - name: Check Terraform
        run: |
          echo "- Terraform"
          if ! command -v terraform &> /dev/null; then
          echo "* Terraform wil be installed."
          brew install terraform
          fi
          terraform --version
        shell: bash

        