name: GitHub Test Toolset Install
on: [push]
jobs:
  check_install:
    name: Test Install Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Install
        name: Test - Check & Install Toolset without override
        uses: ./
      - id: Install_ovveride
        name: Test - Check & Install Toolset with override
        uses: ./
        with:
          OVERRIDE_LOCAL_VERSION: 'true'