name: Test Toolset Install
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths:

      - 'src/*'
      - 'action.yml'
      - '.github/workflows/test.yml'
jobs:
  test_install:
    name: Test - Install Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Install
        name: Test - Check & Install Toolset without override
        uses: ./
      - id: Install_test
        name: Test - Check & Install Toolset when exists
        uses: ./
      - id: Install_override
        name: Test - Check & Install Toolset with override
        uses: ./
        with:
          OVERRIDE_LOCAL_VERSION: 'true'
      - name: Check necessary tools
        run: |
          terraform --version
          tflint --version
          inspec --version
          checkov --version
          jq --version
          xmllint --version
          rpl --version
        shell: bash