name: Test Toolset Install
on: [push]
jobs:
  test_install:
    name: Test - Install Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Install
        name: Test - Check & Install Toolset without override
        uses: ./
      - id: Install_test
        name: Test - Check & Install Toolset when exists
        uses: ./
      - id: Install_override
        name: Test - Check & Install Toolset with override
        uses: ./
        with:
          OVERRIDE_LOCAL_VERSION: 'true'